// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekpdaqynupudvwbeuqdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcGRhcXludXB1ZHZ3YmV1cWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTMxODIsImV4cCI6MjA2MDYyOTE4Mn0.Mg56-VdNPZoa_4FT2YA_H6EAZlD04VZybm4DwjigWjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);